project_id = "dwncekwarwkyjfwztebf"

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.create-order]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.admin-login]
verify_jwt = false
